name: run build
on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm install
      - name: install TypeScript & Vite
        run: npm install --save-dev typescript vite
      - run: npm run build

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with: 
          type: 'zip'
          directory: './dist'
          path: './'
          filename: 'chrome_extension.zip'
          
      - name: artifact move
      - run: mv ./dist/chrome_extension.zip ./

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "chrome_extension.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
