name: run build
on:
  workflow_dispatch:
  create:
    releases:
      - v[0-9]+.[0-9]+.[0-9]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          
      - name: Install dependencies
        run: npm install
        
      - name: install TypeScript & Vite
        run: npm install --save-dev typescript vite
        
      - name: build
        run: npm run build

      - name: Zipping Artifact
        uses: thedoctor0/zip-release@main
        with: 
          type: 'zip'
          directory: './dist'
          path: './'
          filename: 'chrome_extension.zip'

      - name: Artifact move
        run: mv ./dist/chrome_extension.zip ./
        
      - name: Upload Archive
        uses: ncipollo/release-action@v1
        with:
          artifacts: "chrome_extension.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
